version: 2
updates:
- package-ecosystem: "npm"
  directory: "/typescript"
  schedule:
    interval: "weekly"

- package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
