version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/typescript/base/"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/typescript/ethers-v6/"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/typescript/ethers-v5/"
  schedule:
    interval: "weekly"

- package-ecosystem: "pip"
  directory: "/python/scripts/"
  schedule:
    interval: "weekly"

- package-ecosystem: "pip"
  directory: "/python/test/"
  schedule:
    interval: "weekly"
