name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - stable
      - beta
      - develop
  push:
    tags:
      - 'custom-release-*'

env:
  NODE_VERSION: 18
  PYTHON_VERSION: 3.11

jobs:
  typescript:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: typescript/base

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Install project
      run: yarn

    - name: Compile typescript
      run: yarn compile

    - name: Determine version
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "Branch $BRANCH"
        export VERSION=$(bash ../scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        ( test $BRANCH = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
        echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

    - name: Publish NPM package
      run: ../scripts/publish_package.sh
      env:
        BRANCH: ${{ env.BRANCH }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        BASE_PACKAGE: "true"

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: typescript-${{ env.VERSION }}
        prerelease: ${{ env.PRERELEASE }}
        commit: ${{ github.sha }}

  ethers-v5:
    runs-on: ubuntu-latest

    needs:
      typescript

    defaults:
      run:
        working-directory: typescript/ethers-v5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Install base project
      run: |
        yarn ../base
        yarn ../base compile

    - name: Install project
      run: yarn

    - name: Compile typescript
      run: yarn compile

    - name: Determine version
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "Branch $BRANCH"
        export VERSION=$(LAST_EXISTING=true bash ../scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        ( test $BRANCH = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
        echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

    - name: Publish NPM package
      run: ../scripts/publish_package.sh
      env:
        BRANCH: ${{ env.BRANCH }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: typescript-ethers-v5-${{ env.VERSION }}
        prerelease: ${{ env.PRERELEASE }}
        commit: ${{ github.sha }}

  ethers-v6:
    runs-on: ubuntu-latest

    needs:
      typescript

    defaults:
      run:
        working-directory: typescript/ethers-v6

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Install base project
      run: |
        yarn ../base
        yarn ../base compile

    - name: Install project
      run: yarn

    - name: Compile typescript
      run: yarn compile

    - name: Determine version
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "Branch $BRANCH"
        export VERSION=$(LAST_EXISTING=true bash ../scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        ( test $BRANCH = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
        echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

    - name: Publish NPM package
      run: ../scripts/publish_package.sh
      env:
        BRANCH: ${{ env.BRANCH }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: typescript-ethers-v6-${{ env.VERSION }}
        prerelease: ${{ env.PRERELEASE }}
        commit: ${{ github.sha }}

  viem:
    runs-on: ubuntu-latest

    needs:
      typescript

    defaults:
      run:
        working-directory: typescript/viem

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Install base project
      run: |
        yarn ../base
        yarn ../base compile

    - name: Install project
      run: yarn

    - name: Compile typescript
      run: yarn compile

    - name: Determine version
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "Branch $BRANCH"
        export VERSION=$(LAST_EXISTING=true bash ../scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        ( test $BRANCH = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
        echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

    - name: Publish NPM package
      run: ../scripts/publish_package.sh
      env:
        BRANCH: ${{ env.BRANCH }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: typescript-viem-${{ env.VERSION }}
        prerelease: ${{ env.PRERELEASE }}
        commit: ${{ github.sha }}

  python:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install building tools
      run: pip3 install -r scripts/requirements.txt

    - name: Determine version
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "Branch $BRANCH"
        export VERSION=$(bash ./scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        ( test $BRANCH = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
        echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

    - name: Build pip package
      env:
          PYTHONPATH: ./
          VERSION: ${{ env.VERSION }}
      run: ./scripts/build_package.sh

    - name: Publish pip package
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        ./scripts/publish_package.sh

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: python-${{ env.VERSION }}
        prerelease: ${{ env.PRERELEASE }}
        artifacts: python/dist/*
        commit: ${{ github.sha }}
