name: Test

on: [push, pull_request]

env:
  NODE_VERSION: 18

jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "true"

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Ensure Yarn cache folder exists
      run: mkdir -p "$(yarn config get cacheFolder)"

    - name: Install dev tools
      run: yarn

    - name: Check spelling
      run: yarn cspell

  typescript:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    defaults:
      run:
        working-directory: typescript/base

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Ensure Yarn cache folder exists
      run: mkdir -p "$(yarn config get cacheFolder)"

    - name: Install project
      run: yarn

    - name: Run static checks
      run: yarn fullCheck

  ethers-v5:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    defaults:
      run:
        working-directory: typescript/ethers-v5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Ensure Yarn cache folder exists
      run: mkdir -p "$(yarn config get cacheFolder)"

    - name: Install base project
      run: |
        yarn ../base
        yarn ../base compile

    - name: Install project
      run: yarn

    - name: Run static checks
      run: yarn fullCheck

  ethers-v6:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    defaults:
      run:
        working-directory: typescript/ethers-v6

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Ensure Yarn cache folder exists
      run: mkdir -p "$(yarn config get cacheFolder)"

    - name: Install base project
      run: |
        yarn ../base
        yarn ../base compile

    - name: Install project
      run: yarn

    - name: Run static checks
      run: yarn fullCheck

  viem:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    defaults:
      run:
        working-directory: typescript/viem

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Ensure Yarn cache folder exists
      run: mkdir -p "$(yarn config get cacheFolder)"

    - name: Install base project
      run: |
        yarn ../base
        yarn ../base compile

    - name: Install project
      run: yarn

    - name: Run static checks
      run: yarn fullCheck

  python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    defaults:
      run:
        working-directory: python

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install building tools
      run: pip3 install -r scripts/requirements.txt

    - name: Determine version
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "Branch $BRANCH"
        export VERSION=$(bash ./scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        ( test $BRANCH = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
        echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

    - name: Build pip package
      env:
          PYTHONPATH: ./
          VERSION: ${{ env.VERSION }}
      run: ./scripts/build_package.sh

    - name: Install the package
      run: pip3 install -e .

    - name: Install tools
      run: pip3 install -r test/requirements.txt

    - name: Run static checks
      run: scripts/full_check.sh
