name: Test

on: [push, pull_request]

env:
  NODE_VERSION: 18
  # PYTHON_VERSIONS: [3.7, 3.8, 3.9, 3.10, 3.11]

jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      submodules: "true"

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dev tools
      run: yarn

    - name: Check spelling
      run: yarn cspell

  typescript:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18, 19, 20]

    defaults:
      run:
        working-directory: typescript

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install project
      run: yarn

    - name: Run static checks
      run: yarn fullCheck
